version: "3.7"

services:
  db:
    image: mongo
    restart: always
    env_file:
      - ./bot/.env
    volumes:
      - ./db/db_prod:/var/lib/mongodb/data
    

  bot:
    build:
      context: ./bot
      dockerfile: prod.Dockerfile  
    restart: always
    ports:
      - 11311:11311
    volumes:
      - /home/bot_log:/usr/src/app/logs/output_log
    depends_on:
      - db

  
  app:
    build:
      context: ./app
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 11310:80


  # web:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/default_nginx.conf
  #   ports:
  #     - 80:80
  #   command: /bin/bash -c nginx -g 'daemon off;'"