version: "3.7"

services:
  db:
    image: mongo
    restart: always
    env_file:
      - ./bot/.env  

  bot:
    build:
      context: ./bot
      dockerfile: prod.Dockerfile  
    restart: always
    ports:
      - 11311:11311
    volumes:
      - /home/bot_log:/usr/src/app/logs/output_log
    depends_on:
      - db
